export const ENDPOINTS = {
  login: "/users/auth/sign-in",
  register: "/users/auth/sign-up",
  getMe: "/users/getme",
  management: "/management",
  news: "/news",
  socials: "/socials",
  marquees: "/marquees",
  media: "/media",
  message: "/messages",
  mediaByType: "/media/byType",
  activities: "/activities",
  services: "/services",
  updateProfile: "/users/update-profile",
  users: "/user",
  products: "/products",
  vacancies: "/vacancies",
  productsAll: "/products/all",
  contacts: "/contacts",
  departments: "/departments",
  videoGet: "/files/video/stream",
};
